url: jdbc:postgresql://localhost:5432/reading-realm
username: postgres
password: password
driver-class-name: org.postgresql.Driver
author-dataset-file-path: C:\Users\yahya\Downloads\Goodreads Data\author_dataset.csv