url: jdbc:postgresql://localhost:5432/reading_realm
username: postgres
password: password
driver-class-name: org.postgresql.Driver
author-dataset-file-path: /Users/yahyahaji/Documents/GoodReads/author_dataset.csv
goodreads-dataset-file-path: /Users/yahyahaji/Documents/GoodReads/output.json.gz
genres:
  Fantasy:
    - Fantasy
  Science Fiction:
    - Science Fiction
    - Sci-Fi
    - SF
  Mystery:
    - Mystery
  Thriller:
    - Thriller
  Romance:
    - Romance
  Historical Fiction:
    - Historical Fiction
    - Historical
  Horror:
    - Horror
  Adventure:
    - Adventure
  Young Adult:
    - Young Adult
    - YA
  Dystopian:
    - Dystopian
  Memoir:
    - Memoir
  Biography:
    - Biography
    - Bio
  Self-help:
    - Self-help
    - Self Help
  Business:
    - Business
  Classic Literature:
    - Classic Literature
    - Classics
  Poetry:
    - Poetry
  Comedy:
    - Comedy
    - Humor
  Satire:
    - Satire
  Crime:
    - Crime
  Suspense:
    - Suspense
  Non-fiction:
    - Non-fiction
    - Nonfiction
  Travel:
    - Travel
  Autobiography:
    - Autobiography
    - Auto-biography
    - Autobiographical
    - Auto-biographical
    - Autobiographies
  Science:
    - Science
  Philosophy:
    - Philosophy
  Psychology:
    - Psychology
  Religion/Spirituality:
    - Religion/Spirituality
    - Religion
    - Spirituality
    - Religious
    - Spiritual
  Art/Photography:
    - Art/Photography
    - Art
    - Photography
  Cooking/Food:
    - Cooking/Food
    - Cooking
    - Food
  Health/Fitness:
    - Health/Fitness
    - Health
    - Fitness
  Fiction:
    - Fiction
    - Fictional
    - Novel