version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    env_file: .env
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  springboot-app:
    build: .
    container_name: springboot-app
    env_file: .env
    ports:
      - ${SPRINGBOOT_LOCAL_PORT}:${SPRINGBOOT_DOCKER_PORT}
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: local  # Set the active profile to "local"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:${POSTGRES_DOCKER_PORT}/reading-realm
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - gradle-cache:/root/.gradle  # Mount Gradle cache directory as a volume

volumes:
  postgres-data:
  gradle-cache: