package org.pentales.pentalesrest.models.enums

enum class EContentReportReason {

    HARASSMENT,
    HATE_SPEECH,
    VIOLENCE_OR_THREATS,
    CHILD_EXPLOITATION,
    GRAPHIC_CONTENT,
    SPAM_OR_PHISHING,
    IMPERSONATION,
    INTELLECTUAL_PROPERTY_INFRINGEMENT,
    PRIVACY_VIOLATION,
    MISINFORMATION_OR_FAKE_NEWS
}

