spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none # You can use "create" for initial setup or "update" for updates
    show-sql: false # Set to true to see SQL queries in the console
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: prod # Set the active profile here, e.g., "dev" or "prod"
  servlet:
    multipart:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: REPLACE_ME
            client-secret: REPLACE_ME
            redirect-uri: REPLACE_ME
            scope:
              - email
              - profile

server:
  port: 8080 # Specify the port on which your Spring Boot application will run

org:
  pen-tales:
    security:
      jwt:
        secret: secret # Secret key for JWT signing
        expiration: 86400000 # Token validity time in milliseconds
        header: Authorization # Header key for JWT
        prefix: "Bearer " # Prefix for JWT
        issuer: pen-tales # Issuer of the token

    goal:
      default:
        default:
          title: Embrace the Pages
          description: A Year of Literary Exploration

    file:
      upload:
        path: uploads # Path to the directory where the uploaded files will be stored
        allowed-extensions:
          - jpg
          - jpeg
          - png
          - gif
          - bmp
          - webp