spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pen-tales
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # You can use "create" for initial setup or "update" for updates
    show-sql: true # Set to true to see SQL queries in the console
  profiles:
    active: prod # Set the active profile here, e.g., "dev" or "prod"

server:
  port: 8080 # Specify the port on which your Spring Boot application will run

