spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none # You can use "create" for initial setup or "update" for updates
    show-sql: false # Set to true to see SQL queries in the console
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: prod # Set the active profile here, e.g., "dev" or "prod"
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB # Maximum file size for uploads
      max-request-size: 10MB # Maximum request size for uploads
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: REPLACE_ME
            client-secret: REPLACE_ME
            redirect-uri: REPLACE_ME
            scope:
              - email
              - profile

server:
  port: 8443 # Specify the port on which your Spring Boot application will run

org:
  pen-tales:
    security:
      jwt:
        expiration: 86400000 # Token validity time in milliseconds
        header: Authorization # Header key for JWT
        prefix: "Bearer " # Prefix for JWT
        issuer: reading-realm # Issuer of the token

      cors:
        allow-credentials: false
        allowed-methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
          - PATCH
        exposed-headers:
          - Authorization
          - Content-Type
          - Accept
          - X-Requested-With
          - x-xsrf-token
          - Origin
          - Access-Control-Allow-Headers
          - Access-Control-Allow-Origin
          - Access-Control-Request-Method
          - Access-Control-Request-Headers
        allowed-headers:
          - "*"
        max-age: 3600

    goal:
      default:
        title: Embrace the Pages
        description: A Year of Literary Exploration

    file:
      upload:
        path: uploads # Path to the directory where the uploaded files will be stored
        allowed-extensions:
          - jpg
          - jpeg
          - png
          - gif
          - bmp
          - webp
    sentiment-analysis:
      endpoint: http://localhost:5000/evaluate
      interval-rate: 3600000 # Time in milliseconds to wait before sending another request to the sentiment analysis service
